module.exports = {
    'mdx/src/macro.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/mdx/src/macro.vitro.jsx',
    'styled-components/src/big-height.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/styled-components/src/big-height.vitro.jsx',
    'styled-components/src/big-width.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/styled-components/src/big-width.vitro.jsx',
    'styled-components/src/example-styled-components.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/styled-components/src/example-styled-components.vitro.jsx',
    'tailwind/src/example-tailwind.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/tailwind/src/example-tailwind.vitro.jsx',
    'example-package/src/anAwesomeExperiment.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/example-package/src/anAwesomeExperiment.vitro.tsx',
    'example-package/src/anotherExperiment copy copy copy.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/example-package/src/anotherExperiment copy copy copy.vitro.tsx',
    'example-package/src/anotherExperiment copy copy.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/example-package/src/anotherExperiment copy copy.vitro.tsx',
    'example-package/src/anotherExperiment copy.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/example-package/src/anotherExperiment copy.vitro.tsx',
    'example-package/src/anotherExperiment.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/example-package/src/anotherExperiment.vitro.tsx',
    'example-package/src/anotherExperiment1.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/example-package/src/anotherExperiment1.vitro.tsx',
    'example-package/src/example_component.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/example-package/src/example_component.vitro.tsx',
    'example-package/src/experiment1.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/example-package/src/experiment1.vitro.tsx',
    'example-package/src/stillAnotherExperiment.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/example-package/src/stillAnotherExperiment.vitro.tsx',
    'example-package-scope/example-sub-package-1/src/index.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/example-package-scope/example-sub-package-1/src/index.vitro.tsx',
    'example-package-scope/example-sub-package-2/src/index.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/example-package-scope/example-sub-package-2/src/index.vitro.tsx',
}