module.exports = {
    'styled-components/src/big-height.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/styled-components/src/big-height.vitro.jsx',
    'styled-components/src/example-styled-components.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/styled-components/src/example-styled-components.vitro.jsx',
    'tailwind/src/example-tailwind.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/tailwind/src/example-tailwind.vitro.jsx',
    'example-package/src/anAwesomeStory.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/example-package/src/anAwesomeStory.vitro.tsx',
    'example-package/src/anotherStory copy copy copy.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/example-package/src/anotherStory copy copy copy.vitro.tsx',
    'example-package/src/anotherStory copy copy.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/example-package/src/anotherStory copy copy.vitro.tsx',
    'example-package/src/anotherStory copy.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/example-package/src/anotherStory copy.vitro.tsx',
    'example-package/src/anotherStory.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/example-package/src/anotherStory.vitro.tsx',
    'example-package/src/anotherStory1.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/example-package/src/anotherStory1.vitro.tsx',
    'example-package/src/example_component.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/example-package/src/example_component.vitro.tsx',
    'example-package/src/stillAnotherStory.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/example-package/src/stillAnotherStory.vitro.tsx',
    'example-package/src/story1.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/example-package/src/story1.vitro.tsx',
    'example-package-scope/example-sub-package-1/src/index.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/example-package-scope/example-sub-package-1/src/index.vitro.tsx',
    'example-package-scope/example-sub-package-2/src/index.vitro': '/Users/morse/Documents/GitHub/react-comics/examples/example-package-scope/example-sub-package-2/src/index.vitro.tsx',
}